/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import model.Person;
import model.PersonDirectory;
/**
 *
 * @author hardishah
 */
public class CreateJPanel extends javax.swing.JPanel {
    Person person;
    PersonDirectory personDirectory;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(PersonDirectory pd) {
        personDirectory = pd;
        initComponents();
        if (personDirectory.getHistory().size()==0){
        Person person1 = personDirectory.addNewPerson();
            person1.setFirstName("Joey");
            person1.setAge("50".getBytes()[0]);
            person1.setLastName("Tribbiani");
            person1.setSsn("123456789");
            person1.setHomeAddress("Newton","MA",Integer.valueOf("12345"),"Los Angeles",Short.valueOf("1"),Long.valueOf("8575647680"));
            person1.setWorkAddress("Newton","MA",Integer.valueOf("12345"),"Los Angeles",Short.valueOf("1"),Long.valueOf("8575647680"));
            
            Person person2 = personDirectory.addNewPerson();
            person2.setFirstName("Rachel");
            person2.setAge("30".getBytes()[0]);
            person2.setLastName("Green");
            person2.setSsn("123456789");
            person2.setHomeAddress("Sherman Oaks","California",Integer.valueOf("12345"),"Brooklyn",Short.valueOf("1"),Long.valueOf("8575647680"));
            person2.setWorkAddress("Sherman Oaks","California",Integer.valueOf("12345"),"Brooklyn",Short.valueOf("1"),Long.valueOf("8575647680"));
            
            Person person3 = personDirectory.addNewPerson();
            person3.setFirstName("Monica");
            person3.setAge("50".getBytes()[0]);
            person3.setLastName("Geller");
            person3.setSsn("123456789");
            person3.setHomeAddress("Birmingham","Alabama",Integer.valueOf("12345"),"London",Short.valueOf("1"),Long.valueOf("8575647680"));
            person3.setWorkAddress("Birmingham"," Alabama",Integer.valueOf("12345"),"London",Short.valueOf("1"),Long.valueOf("8575647680"));
            
            Person person4 = personDirectory.addNewPerson();
            person4.setFirstName("Ross");
            person4.setAge("30".getBytes()[0]);
            person4.setLastName("Geller");
            person4.setSsn("123456789");
            person4.setHomeAddress("Wakanda"," Alabama",Integer.valueOf("12345"),"Wakanda",Short.valueOf("1"),Long.valueOf("8575647680"));
            person4.setWorkAddress("Wakanda","Alabama",Integer.valueOf("12345"),"Wakanda",Short.valueOf("1"),Long.valueOf("8575647680"));
            
            Person person5 = personDirectory.addNewPerson();
            person5.setFirstName("Phoebe");
            person5.setAge("30".getBytes()[0]);
            person5.setLastName("Buffay");
            person5.setSsn("23456789");
            person5.setHomeAddress("Asgard","Heaven",Integer.valueOf("12345"),"Asgard",Short.valueOf("1"),Long.valueOf("8575647680"));
            person5.setWorkAddress("Asgard","Heaven",Integer.valueOf("12345"),"Asgard",Short.valueOf("1"),Long.valueOf("8575647680"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        pnlWorkAddress = new javax.swing.JPanel();
        txtPhoneWork = new javax.swing.JTextField();
        txtStreetWork = new javax.swing.JTextField();
        txtUnitWork = new javax.swing.JTextField();
        txtZipWork = new javax.swing.JTextField();
        txtCityWork = new javax.swing.JTextField();
        txtStateWork = new javax.swing.JTextField();
        lblStreetW = new javax.swing.JLabel();
        lblUnitW = new javax.swing.JLabel();
        lblCityW = new javax.swing.JLabel();
        lblStateW = new javax.swing.JLabel();
        lblZipW = new javax.swing.JLabel();
        lblPhoneW = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        pnlHomeAddress = new javax.swing.JPanel();
        txtPhoneHome = new javax.swing.JTextField();
        txtStreetHome = new javax.swing.JTextField();
        txtUnitHome = new javax.swing.JTextField();
        txtZipHome = new javax.swing.JTextField();
        txtCityHome = new javax.swing.JTextField();
        txtStateHome = new javax.swing.JTextField();
        lblStreet = new javax.swing.JLabel();
        lblUnit = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZip = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        lblWorkAddress = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        detailslabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 255));

        txtFirstName.setToolTipText("");
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        txtLastName.setToolTipText("");
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        txtSSN.setToolTipText("");

        txtAge.setToolTipText("");

        pnlWorkAddress.setBackground(new java.awt.Color(0, 153, 255));

        lblStreetW.setText("Street");

        lblUnitW.setText("Unit");

        lblCityW.setText("City");

        lblStateW.setText("State");

        lblZipW.setText("Zip");

        lblPhoneW.setText("Phone");

        javax.swing.GroupLayout pnlWorkAddressLayout = new javax.swing.GroupLayout(pnlWorkAddress);
        pnlWorkAddress.setLayout(pnlWorkAddressLayout);
        pnlWorkAddressLayout.setHorizontalGroup(
            pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWorkAddressLayout.createSequentialGroup()
                .addGroup(pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlWorkAddressLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblZipW)
                        .addGap(18, 18, 18)
                        .addComponent(txtZipWork))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWorkAddressLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWorkAddressLayout.createSequentialGroup()
                                .addComponent(lblCityW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCityWork, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWorkAddressLayout.createSequentialGroup()
                                .addComponent(lblStreetW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStreetWork, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(58, 58, 58)
                .addGroup(pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlWorkAddressLayout.createSequentialGroup()
                        .addGroup(pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUnitW)
                            .addComponent(lblPhoneW))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneWork, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitWork, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(pnlWorkAddressLayout.createSequentialGroup()
                        .addComponent(lblStateW)
                        .addGap(18, 18, 18)
                        .addComponent(txtStateWork, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        pnlWorkAddressLayout.setVerticalGroup(
            pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWorkAddressLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStreetW)
                    .addComponent(lblUnitW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityW)
                    .addComponent(txtStateWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStateW))
                .addGroup(pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWorkAddressLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtZipWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZipW))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWorkAddressLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlWorkAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoneWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneW))
                        .addGap(40, 40, 40))))
        );

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        pnlHomeAddress.setBackground(new java.awt.Color(51, 153, 255));
        pnlHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        pnlHomeAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtPhoneHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneHomeActionPerformed(evt);
            }
        });

        txtZipHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipHomeActionPerformed(evt);
            }
        });

        txtCityHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityHomeActionPerformed(evt);
            }
        });

        txtStateHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateHomeActionPerformed(evt);
            }
        });

        lblStreet.setText("Street");

        lblUnit.setText("Unit");

        lblCity.setText("City");

        lblState.setText("State");

        lblZip.setText("Zip");

        lblPhone.setText("Phone");

        javax.swing.GroupLayout pnlHomeAddressLayout = new javax.swing.GroupLayout(pnlHomeAddress);
        pnlHomeAddress.setLayout(pnlHomeAddressLayout);
        pnlHomeAddressLayout.setHorizontalGroup(
            pnlHomeAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeAddressLayout.createSequentialGroup()
                .addGroup(pnlHomeAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeAddressLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblZip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtZipHome, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                    .addGroup(pnlHomeAddressLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblStreet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStreetHome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeAddressLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCityHome)))
                .addGap(30, 30, 30)
                .addGroup(pnlHomeAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblState, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUnit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHomeAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStateHome, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(txtPhoneHome, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(txtUnitHome))
                .addGap(25, 25, 25))
        );
        pnlHomeAddressLayout.setVerticalGroup(
            pnlHomeAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeAddressLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlHomeAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStreet)
                    .addComponent(lblUnit))
                .addGroup(pnlHomeAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeAddressLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(pnlHomeAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCityHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCity)
                            .addComponent(lblState)
                            .addComponent(txtStateHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlHomeAddressLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlHomeAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoneHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone)
                            .addComponent(txtZipHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZip))
                        .addGap(49, 49, 49))))
        );

        lblHomeAddress.setText("Home Address");

        lblWorkAddress.setText("Work Address");

        lblFirstName.setBackground(new java.awt.Color(204, 204, 255));
        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblSSN.setText("Social Security Number");

        lblAge.setText("Age");

        detailslabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        detailslabel.setText("        Personal Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(pnlHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(pnlWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(lblHomeAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWorkAddress)
                .addGap(356, 356, 356))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSSN)
                            .addComponent(lblAge)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSSN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(detailslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstName))
                        .addGap(18, 18, 18)
                        .addComponent(lblLastName))
                    .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSN))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(btnCreate)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:

        
        if (txtFirstName.getText().isBlank()||txtLastName.getText().isBlank()||txtAge.getText().isBlank()||txtSSN.getText().isBlank()||txtStreetHome.getText().isBlank()||txtStateHome.getText().isBlank()||txtZipHome.getText().isBlank()||txtCityHome.getText().isBlank()||txtUnitHome.getText().isBlank()||txtPhoneWork.getText().isBlank()||txtUnitWork.getText().isBlank()||txtCityWork.getText().isBlank()||txtZipWork.getText().isBlank()||txtStateWork.getText().isBlank()||txtStreetWork.getText().isBlank())
            JOptionPane.showMessageDialog(this, "Something is empty..", "Information", JOptionPane. INFORMATION_MESSAGE) ;
        else{
            
            try{
                Integer.parseInt(txtAge.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Age is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Integer.parseInt(txtSSN.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "SSN is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Integer.parseInt(txtZipHome.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Home zip is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Integer.parseInt(txtZipWork.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Work zip is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            }
            
            try{
                Long.parseLong(txtPhoneHome.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Home Phone is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Long.parseLong(txtPhoneWork.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Work Phone is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Integer.parseInt(txtUnitHome.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Home unit is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Integer.parseInt(txtUnitWork.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Work unit is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            
                Person person = personDirectory.addNewPerson();
                person.setFirstName(txtFirstName.getText());
                System.out.println(txtAge);
                person.setAge(Byte.valueOf(txtAge.getText()));
                person.setLastName(txtLastName.getText());
                person.setSsn(txtSSN.getText());
                person.setHomeAddress(txtStreetHome.getText(),txtStateHome.getText(),Integer.valueOf(txtZipHome.getText()),txtCityHome.getText(),Short.valueOf(txtUnitHome.getText()),Long.valueOf(txtPhoneHome.getText()));
                person.setWorkAddress(txtStreetWork.getText(),txtStateWork.getText(),Integer.valueOf(txtZipWork.getText()),txtCityWork.getText(),Short.valueOf(txtUnitWork.getText()),Long.valueOf(txtPhoneWork.getText()));
        
            JOptionPane.showMessageDialog(this, "Person successfully created.", "Information", JOptionPane. INFORMATION_MESSAGE) ;
            txtFirstName.setText("");
            txtLastName.setText("");
            txtAge.setText("");
            txtSSN.setText("");
            txtStreetHome.setText("");
            txtStateHome.setText("");
            txtZipHome.setText("");
            txtCityHome.setText("");
            txtUnitHome.setText("");
            txtPhoneHome.setText("");
            txtStreetWork.setText("");
            txtStateWork.setText("");
            txtZipWork.setText("");
            txtCityWork.setText("");
            txtUnitWork.setText("");
            txtPhoneWork.setText("");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtZipHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipHomeActionPerformed

    private void txtStateHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateHomeActionPerformed

    private void txtPhoneHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneHomeActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtCityHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel detailslabel;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCityW;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneW;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStateW;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblStreetW;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JLabel lblUnitW;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JLabel lblZip;
    private javax.swing.JLabel lblZipW;
    private javax.swing.JPanel pnlHomeAddress;
    private javax.swing.JPanel pnlWorkAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityHome;
    private javax.swing.JTextField txtCityWork;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneHome;
    private javax.swing.JTextField txtPhoneWork;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtStateHome;
    private javax.swing.JTextField txtStateWork;
    private javax.swing.JTextField txtStreetHome;
    private javax.swing.JTextField txtStreetWork;
    private javax.swing.JTextField txtUnitHome;
    private javax.swing.JTextField txtUnitWork;
    private javax.swing.JTextField txtZipHome;
    private javax.swing.JTextField txtZipWork;
    // End of variables declaration//GEN-END:variables
}
