/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author hardishah
 */
public class ViewSearchJPanel extends javax.swing.JPanel {
    PersonDirectory personDirectory;
    JPanel detailsJPanel;
    Person foundPerson;
    /**
     * Creates new form ViewSearchJPanel
     */
    public ViewSearchJPanel(JPanel container, Person p, boolean updateFlag) {
        detailsJPanel = container;
        foundPerson = p;
        initComponents();
        txtAge.setText(Byte.toString(foundPerson.getAge()));
        txtCityH.setText(foundPerson.homeAddress.getCity());
        txtCityW.setText ( foundPerson.workAddress.getCity());
        txtFirstName.setText(foundPerson.getFirstName());
        txtLastName.setText(foundPerson.getLastName());
        txtPhoneH.setText ( Long.toString(foundPerson.homeAddress.getPhone()));
        txtPhoneW.setText ( Long.toString(foundPerson.workAddress.getPhone()));
        txtSsn.setText( foundPerson.getSsn());
        txtStateH.setText(foundPerson.homeAddress.getState());
        txtStateW.setText ( foundPerson.workAddress.getState());
        txtStreetH.setText ( foundPerson.homeAddress.getStreet());
        txtStreetW.setText( foundPerson.workAddress.getStreet());
        txtUnitH.setText( Integer.toString(foundPerson.homeAddress.getUnit()));
        txtUnitW.setText( Integer.toString(foundPerson.workAddress.getUnit()));
        txtZipH.setText( Integer.toString(foundPerson.homeAddress.getZip()));
        txtZipW.setText ( Integer.toString(foundPerson.workAddress.getZip()));
        
        
        if (!updateFlag){
            txtAge.setEditable(false);
            txtCityH.setEditable(false);
            txtCityW.setEditable(false);
            txtFirstName.setEditable(false);
            txtLastName.setEditable(false);
            txtPhoneH.setEditable(false);
            txtPhoneW.setEditable(false);
            txtSsn.setEditable(false);
            txtStateH.setEditable(false);
            txtStateW.setEditable(false);
            txtStreetH.setEditable(false);
            txtStreetW.setEditable(false);
            txtUnitH.setEditable(false);
            txtUnitW.setEditable(false);
            txtZipH.setEditable(false);
            txtZipW.setEditable(false);
            btnSave.setEnabled (false);
            btnUpdate. setEnabled (true);
        }
        else{
            btnSave.setEnabled (true);
            btnUpdate. setEnabled (false);
            txtAge.setEditable(true);
        txtCityH.setEditable(true);
        txtCityW.setEditable(true);
        txtFirstName.setEditable(true);
        txtLastName.setEditable(true);
        txtPhoneH.setEditable(true);
        txtPhoneW.setEditable(true);
        txtSsn.setEditable(true);
        txtStateH.setEditable(true);
        txtStateW.setEditable(true);
        txtStreetH.setEditable(true);
        txtStreetW.setEditable(true);
        txtUnitH.setEditable(true);
        txtUnitW.setEditable(true);
        txtZipH.setEditable(true);
        txtZipW.setEditable(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtStreetH = new javax.swing.JTextField();
        labelHomeUnit = new javax.swing.JLabel();
        txtUnitH = new javax.swing.JTextField();
        lblHState = new javax.swing.JLabel();
        txtStateH = new javax.swing.JTextField();
        labelHomeCity = new javax.swing.JLabel();
        txtCityH = new javax.swing.JTextField();
        lblHomeStreet = new javax.swing.JLabel();
        txtPhoneH = new javax.swing.JTextField();
        lblWStreet = new javax.swing.JLabel();
        txtStreetW = new javax.swing.JTextField();
        lblWorkUnit = new javax.swing.JLabel();
        txtUnitW = new javax.swing.JTextField();
        lblWorkState = new javax.swing.JLabel();
        txtStateW = new javax.swing.JTextField();
        labelHPhone = new javax.swing.JLabel();
        lblWorkCity = new javax.swing.JLabel();
        txtCityW = new javax.swing.JTextField();
        labelWorkPhone = new javax.swing.JLabel();
        txtPhoneW = new javax.swing.JTextField();
        labelWorkZip = new javax.swing.JLabel();
        txtZipW = new javax.swing.JTextField();
        lblHZip = new javax.swing.JLabel();
        txtZipH = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        lblFirstName.setText("First Name");

        txtFirstName.setEditable(false);
        txtFirstName.setPreferredSize(new java.awt.Dimension(100, 23));

        lblLastName.setText("Last Name");

        txtLastName.setEditable(false);
        txtLastName.setPreferredSize(new java.awt.Dimension(100, 23));

        lblAge.setText("Age");

        txtAge.setEditable(false);
        txtAge.setPreferredSize(new java.awt.Dimension(100, 23));

        lblSSN.setText("Social Security Number");

        txtSsn.setEditable(false);
        txtSsn.setPreferredSize(new java.awt.Dimension(100, 23));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtStreetH.setEditable(false);
        txtStreetH.setPreferredSize(new java.awt.Dimension(100, 23));

        labelHomeUnit.setText("Home Unit");

        txtUnitH.setEditable(false);
        txtUnitH.setPreferredSize(new java.awt.Dimension(100, 23));

        lblHState.setText("Home State");

        txtStateH.setEditable(false);
        txtStateH.setPreferredSize(new java.awt.Dimension(100, 23));

        labelHomeCity.setText("Home City");

        txtCityH.setEditable(false);
        txtCityH.setPreferredSize(new java.awt.Dimension(100, 23));

        lblHomeStreet.setText("Home Street");

        txtPhoneH.setEditable(false);
        txtPhoneH.setPreferredSize(new java.awt.Dimension(100, 23));

        lblWStreet.setText("Work Street");

        txtStreetW.setEditable(false);
        txtStreetW.setPreferredSize(new java.awt.Dimension(100, 23));

        lblWorkUnit.setText("Work Unit");

        txtUnitW.setEditable(false);
        txtUnitW.setPreferredSize(new java.awt.Dimension(100, 23));

        lblWorkState.setText("Work State");

        txtStateW.setEditable(false);
        txtStateW.setPreferredSize(new java.awt.Dimension(100, 23));

        labelHPhone.setText("Home Phone");

        lblWorkCity.setText("Work City");

        txtCityW.setEditable(false);
        txtCityW.setPreferredSize(new java.awt.Dimension(100, 23));

        labelWorkPhone.setText("Work Phone");

        txtPhoneW.setEditable(false);
        txtPhoneW.setPreferredSize(new java.awt.Dimension(100, 23));

        labelWorkZip.setText("Work Zip");

        txtZipW.setEditable(false);
        txtZipW.setPreferredSize(new java.awt.Dimension(100, 23));

        lblHZip.setText("Home Zip");

        txtZipH.setEditable(false);
        txtZipH.setPreferredSize(new java.awt.Dimension(100, 23));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(148, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHState)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStateH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHomeStreet)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStreetH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblWStreet)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStreetW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblWorkUnit)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUnitW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFirstName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblLastName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblWorkState)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStateW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelHPhone)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPhoneH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblAge)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblWorkCity)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                                    .addComponent(txtCityW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSSN)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelWorkPhone)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                    .addComponent(txtPhoneW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelWorkZip)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                    .addComponent(txtZipW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelHomeUnit)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUnitH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelHomeCity)
                                    .addGap(213, 213, 213))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHZip)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtZipH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtCityH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeStreet)
                    .addComponent(txtStreetH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHomeUnit)
                    .addComponent(txtUnitH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHState)
                    .addComponent(txtStateH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHomeCity)
                    .addComponent(txtCityH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHZip)
                    .addComponent(txtZipH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHPhone)
                    .addComponent(txtPhoneH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWStreet)
                    .addComponent(txtStreetW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkUnit)
                    .addComponent(txtUnitW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkState)
                    .addComponent(txtStateW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkCity)
                    .addComponent(txtCityW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWorkPhone)
                    .addComponent(txtPhoneW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWorkZip)
                    .addComponent(txtZipW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAge, txtCityH, txtCityW, txtFirstName, txtLastName, txtPhoneH, txtPhoneW, txtSsn, txtStateH, txtStateW, txtStreetH, txtStreetW, txtUnitH, txtUnitW, txtZipH, txtZipW});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        detailsJPanel.remove(this);
        CardLayout layout = (CardLayout) detailsJPanel.getLayout();
        layout. previous (detailsJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtAge.setEditable(true);
        txtCityH.setEditable(true);
        txtCityW.setEditable(true);
        txtFirstName.setEditable(true);
        txtLastName.setEditable(true);
        txtPhoneH.setEditable(true);
        txtPhoneW.setEditable(true);
        txtSsn.setEditable(true);
        txtStateH.setEditable(true);
        txtStateW.setEditable(true);
        txtStreetH.setEditable(true);
        txtStreetW.setEditable(true);
        txtUnitH.setEditable(true);
        txtUnitW.setEditable(true);
        txtZipH.setEditable(true);
        txtZipW.setEditable(true);
        btnSave.setEnabled (true);
        btnUpdate.setEnabled (false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtAge.getText().isBlank() || txtCityH.getText().isBlank() || txtCityW.getText().isBlank() || txtFirstName.getText().isBlank() || txtLastName.getText().isBlank() || txtPhoneH.getText().isBlank() || txtPhoneW.getText().isBlank() || txtSsn.getText().isBlank() || txtStateH.getText().isBlank() || txtStateW.getText().isBlank() || txtStreetH.getText().isBlank() || txtStreetW.getText().isBlank() || txtUnitH.getText().isBlank() || txtUnitW.getText().isBlank() || txtZipH.getText().isBlank() || txtZipW.getText().isBlank()){
            JOptionPane.showMessageDialog (null, "All fields are mandatory.");
            return;
        }
        
        try{
                Integer.parseInt(txtAge.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Age is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
                return;
            }
            
            try{
                Integer.parseInt(txtSsn.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "SSN is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
                return;
            }
            
            try{
                Integer.parseInt(txtZipH.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Home zip is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Integer.parseInt(txtZipW.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Work zip is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Long.parseLong(txtPhoneH.getText());
            
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Home Phone is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Long.parseLong(txtPhoneW.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Work Phone is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
               Short.parseShort(txtUnitH.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Home unit is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Short.parseShort(txtUnitH.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Work unit is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
//        Person person = personDirectory.addNewPerson();
        foundPerson.setFirstName(txtFirstName.getText());
        foundPerson.setAge(txtAge.getText().getBytes()[0]);
        foundPerson.setLastName(txtLastName.getText());
        foundPerson.setSsn(txtSsn.getText());
        foundPerson.setHomeAddress(txtStreetH.getText(),txtStateH.getText(),Integer.valueOf(txtZipH.getText()),txtCityH.getText(),Short.valueOf(txtUnitH.getText()),Long.valueOf(txtPhoneH.getText()));
        foundPerson.setWorkAddress(txtStreetW.getText(),txtStateW.getText(),Integer.valueOf(txtZipW.getText()),txtCityW.getText(),Short.valueOf(txtUnitW.getText()),Long.valueOf(txtPhoneW.getText()));
        
        
        JOptionPane.showMessageDialog(null, "Account successfully updated.", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        txtAge.setEditable(false);
        txtCityH.setEditable(false);
        txtCityW.setEditable(false);
        txtFirstName.setEditable(false);
        txtLastName.setEditable(false);
        txtPhoneH.setEditable(false);
        txtPhoneW.setEditable(false);
        txtSsn.setEditable(false);
        txtStateH.setEditable(false);
        txtStateW.setEditable(false);
        txtStreetH.setEditable(false);
        txtStreetW.setEditable(false);
        txtUnitH.setEditable(false);
        txtUnitW.setEditable(false);
        txtZipH.setEditable(false);
        txtZipW.setEditable(false);
        
        btnSave.setEnabled (false);
        btnUpdate. setEnabled (true);
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel labelHPhone;
    private javax.swing.JLabel labelHomeCity;
    private javax.swing.JLabel labelHomeUnit;
    private javax.swing.JLabel labelWorkPhone;
    private javax.swing.JLabel labelWorkZip;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHState;
    private javax.swing.JLabel lblHZip;
    private javax.swing.JLabel lblHomeStreet;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblWStreet;
    private javax.swing.JLabel lblWorkCity;
    private javax.swing.JLabel lblWorkState;
    private javax.swing.JLabel lblWorkUnit;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityH;
    private javax.swing.JTextField txtCityW;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneH;
    private javax.swing.JTextField txtPhoneW;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtStateH;
    private javax.swing.JTextField txtStateW;
    private javax.swing.JTextField txtStreetH;
    private javax.swing.JTextField txtStreetW;
    private javax.swing.JTextField txtUnitH;
    private javax.swing.JTextField txtUnitW;
    private javax.swing.JTextField txtZipH;
    private javax.swing.JTextField txtZipW;
    // End of variables declaration//GEN-END:variables
}
