/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author rohanjauhari
 */
public class CreateJPanel extends javax.swing.JPanel {
    Product product;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(Product p) {
        product = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        labelDriversLicenseNumber = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        labelDescription1 = new javax.swing.JLabel();
        txtFaxNumber = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        labelSocialSecurityNumber = new javax.swing.JLabel();
        txtAddressLine1 = new javax.swing.JTextField();
        labelAddressLine1 = new javax.swing.JLabel();
        txtDLN = new javax.swing.JTextField();
        txtDLS = new javax.swing.JTextField();
        labelName2 = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        labelPhone = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        labelCity = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        State = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        labelZip = new javax.swing.JLabel();
        txtAddressLine2 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        labelTelephoneNumber = new javax.swing.JLabel();
        labelFaxNumber = new javax.swing.JLabel();
        txtMiddleName = new javax.swing.JTextField();
        labelMiddleName = new javax.swing.JLabel();
        labelMartialstatus = new javax.swing.JLabel();
        txtMartialStatus = new javax.swing.JTextField();
        labelNationality = new javax.swing.JLabel();
        txtNationality = new javax.swing.JTextField();
        labelDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        labelHobbies = new javax.swing.JLabel();
        txtHobbies = new javax.swing.JTextField();
        labelLanguages = new javax.swing.JLabel();
        txtLanguages = new javax.swing.JTextField();

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Create Person Profile");

        labelFirstName.setText("First Name");

        labelLastName.setText("Last Name");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        labelDriversLicenseNumber.setText("Drivers License Number");

        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });

        labelDescription1.setText("Drivers License State");

        txtFaxNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumberActionPerformed(evt);
            }
        });

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        labelSocialSecurityNumber.setText("Social Security Number");

        txtAddressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressLine1ActionPerformed(evt);
            }
        });

        labelAddressLine1.setText("Address Line 1");

        txtDLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDLNActionPerformed(evt);
            }
        });

        txtDLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDLSActionPerformed(evt);
            }
        });

        labelName2.setText("Address Line 2");

        labelEmail.setText("Email");

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        labelPhone.setText("Phone");

        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });

        txtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameActionPerformed(evt);
            }
        });

        labelCity.setText("City");

        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        State.setText("State");

        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });

        labelZip.setText("Zip");

        txtAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressLine2ActionPerformed(evt);
            }
        });

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        labelTelephoneNumber.setText("Telephone Number");

        labelFaxNumber.setText("Fax Number");

        txtMiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiddleNameActionPerformed(evt);
            }
        });

        labelMiddleName.setText("Middle Name");

        labelMartialstatus.setText("Martial Status");

        txtMartialStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMartialStatusActionPerformed(evt);
            }
        });

        labelNationality.setText("Nationality");

        txtNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNationalityActionPerformed(evt);
            }
        });

        labelDOB.setText("Date of Birth");

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        labelHobbies.setText("Hobbies");

        txtHobbies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHobbiesActionPerformed(evt);
            }
        });

        labelLanguages.setText("Languages");

        txtLanguages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLanguagesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(State, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelZip, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMiddleName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTelephoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFaxNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelSocialSecurityNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMartialstatus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAddressLine1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNationality, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelName2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDriversLicenseNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDescription1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDOB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLanguages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCity, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelHobbies, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLastname, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZip)
                    .addComponent(txtAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(txtMiddleName, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(txtFaxNumber)
                    .addComponent(txtSSN)
                    .addComponent(txtAddressLine1)
                    .addComponent(txtMartialStatus)
                    .addComponent(txtDLN, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(txtNationality)
                    .addComponent(txtDLS)
                    .addComponent(txtPhone)
                    .addComponent(txtEmail)
                    .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(txtDOB)
                    .addComponent(txtHobbies)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(txtLanguages))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAddressLine1, txtAddressLine2, txtCity, txtDLN, txtDLS, txtDOB, txtEmail, txtFaxNumber, txtFirstname, txtHobbies, txtLanguages, txtLastname, txtMartialStatus, txtMiddleName, txtNationality, txtPhone, txtSSN, txtState, txtTel, txtZip});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMiddleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDriversLicenseNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescription1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSocialSecurityNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAddressLine1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(State)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelZip)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelephoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFaxNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMartialstatus)
                    .addComponent(txtMartialStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNationality)
                    .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHobbies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHobbies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelCity, labelEmail, labelHobbies, labelPhone});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String firstname = txtFirstname.getText();
        String middlename = txtMiddleName.getText();
        String lastname = txtLastname.getText();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String drivers_lisence_number = txtDLN.getText();
        String drivers_lisence_state = txtDLS.getText();
        String social_security_number = txtSSN.getText();
        String address_line_1 = txtAddressLine1.getText();
        String address_line_2 = txtAddressLine2.getText();
        String city = txtCity.getText();
        String state = txtState.getText();
        String zip = txtZip.getText();
        String telephone_number = txtTel.getText();
        String fax = txtFaxNumber.getText();
        String hobbies = txtHobbies.getText();
        String languages = txtLanguages.getText();
        String DOB = txtDOB.getText();
        String status = txtMartialStatus.getText();
        String nationality = txtNationality.getText();
        
        boolean isValid = true;

        
        // Validate Zip Code
        if (!zip.matches("\\d{5}(-\\d{4})?")) {
        JOptionPane.showMessageDialog(this, "Invalid Zip Code! Enter a valid 5 or 9 digit ZIP.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        isValid = false;
        }

        if(isValid){
        product.setFirstName(firstname);
        product.setMiddleName(middlename);
        product.setLastName(lastname);
        product.setEmail(email);
        product.setPhone(phone);
        product.setDriversLicenseNumber(drivers_lisence_number);
        product.setDriversLicenseState(drivers_lisence_state);
        product.setSocialSecurityNumber(social_security_number);
        product.setAddressLine1(address_line_1);
        product.setAddressLine2(address_line_2);
        product.setCity(city);
        product.setState(state);
        product.setZip(zip);
        product.setTelephoneNumber(telephone_number);
        product.setFaxNumber(fax);
        product.setHobbies(hobbies);
        product.setLanguages(languages);
        product.setDob(DOB);
        product.setStatus(status);
        product.setNationality(nationality);
        
        
        
        
        JOptionPane.showMessageDialog(this,"Profile Saved","Success",JOptionPane.PLAIN_MESSAGE);
        
        txtAddressLine1.setText("");
        txtAddressLine2.setText("");
        txtCity.setText("");
        txtDLN.setText("");
        txtDLS.setText("");
        txtEmail.setText("");
        txtFaxNumber.setText("");
        txtFirstname.setText("");
        txtLastname.setText("");
        txtPhone.setText("");
        txtSSN.setText("");
        txtState.setText("");
        txtTel.setText("");
        txtZip.setText("");
        txtMiddleName.setText("");
        txtNationality.setText("");
        txtLanguages.setText("");
        txtHobbies.setText("");
        txtDOB.setText("");
        txtMartialStatus.setText("");
        
        }
                
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtDLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDLNActionPerformed

    private void txtAddressLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressLine1ActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtFaxNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumberActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressLine2ActionPerformed

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastnameActionPerformed

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtDLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDLSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDLSActionPerformed

    private void txtMiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiddleNameActionPerformed

    private void txtMartialStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMartialStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMartialStatusActionPerformed

    private void txtNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalityActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtHobbiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHobbiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHobbiesActionPerformed

    private void txtLanguagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLanguagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLanguagesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel State;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel labelAddressLine1;
    private javax.swing.JLabel labelCity;
    private javax.swing.JLabel labelDOB;
    private javax.swing.JLabel labelDescription1;
    private javax.swing.JLabel labelDriversLicenseNumber;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFaxNumber;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelHobbies;
    private javax.swing.JLabel labelLanguages;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelMartialstatus;
    private javax.swing.JLabel labelMiddleName;
    private javax.swing.JLabel labelName2;
    private javax.swing.JLabel labelNationality;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelSocialSecurityNumber;
    private javax.swing.JLabel labelTelephoneNumber;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelZip;
    private javax.swing.JTextField txtAddressLine1;
    private javax.swing.JTextField txtAddressLine2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDLN;
    private javax.swing.JTextField txtDLS;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtHobbies;
    private javax.swing.JTextField txtLanguages;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtMartialStatus;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
